import { Routes } from '@angular/router';
import { Home } from './pages/home/home';
import { Products } from './pages/products/products';
import { ProductDetail } from './pages/product-detail/product-detail';
import { Cart } from './pages/cart/cart';
import { Auth } from './pages/auth/auth';
import { Checkout } from './pages/checkout/checkout';
import { Profile } from './pages/profile/profile';
import { Orders } from './pages/orders/orders';
import { CreateProduct } from './pages/create-product/create-product';
import { Wishlist } from './pages/wishlist/wishlist';
import { Farmers } from './pages/farmers/farmers';
import { Brands } from './pages/brands/brands';
import { Seasonal } from './pages/seasonal/seasonal';
import { Nursery } from './pages/nursery/nursery';
import { LocalSpecials } from './pages/local-specials/local-specials';

export const routes: Routes = [
  { path: '', component: Home },
  { path: 'home', component: Home },
  { path: 'products', component: Products },
  { path: 'products/:category', component: Products },
  { path: 'product/:id', component: ProductDetail },
  { path: 'cart', component: Cart },
  { path: 'checkout', component: Checkout },
  { path: 'orders', component: Orders },
  { path: 'create-product', component: CreateProduct },
  { path: 'wishlist', component: Wishlist },
  { path: 'farmers', component: Farmers },
  { path: 'brands', component: Brands },
  { path: 'seasonal', component: Seasonal },
  { path: 'nursery', component: Nursery },
  { path: 'specials', component: LocalSpecials },
  { path: 'profile', component: Profile },
  { path: 'auth', component: Auth },
  { path: 'login', component: Auth },
  { path: 'register', component: Auth },
  { path: '**', redirectTo: '' }
];
